AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hackathon Prototype ver2

Globals:
  Function:
    Tracing: Active
    Runtime: java17
    Timeout: 30
    MemorySize: 2048


Resources:
#  MyApi:
#    Type: AWS::ApiGateway::RestApi
#    Properties:
#      Name: PetCare API


  HackathonPrototypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AWSLambda_FullAccess
      CodeUri: target/hackathon-proto-springboot-0.0.1-SNAPSHOT-lambda.jar
      Handler: team.gpt2p5.hackathonprotospringboot.LambdaHandler::handleRequest
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

#Outputs:
#  HackathonPrototypeAPI:
#    Description: URL for application
#    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.ap-southeast-4.amazonaws.com/petcare'
#    Export:
#      Name: HackathonPrototypeAPI